#
# Global-configurations
#

equals(SKIP_XD_GLOBAL_CONF, true): return()
SKIP_XD_GLOBAL_CONF = true


# Intentionally not `$$shadowed($$PWD)`.
XD_BUILD_TREE=$$PWD
CONFIG += QTDIR_build

# Disables perl `mkspecs/features/qt_module_headers.prf` related warnings.
CONFIG += no_perl

load(qt_build_config)
CONFIG += warning_clean

# In case only release builds crash, debug after rebuilding said release with:
#CONFIG += force_debug_info_full

QT_SOURCE_TREE = $$PWD
QT_BUILD_TREE = $$XD_BUILD_TREE

# WARNING: below overrides header-include paths
# (hence either don't change this, or rename the folders,
# like "./include/QtCore/5.6.3" folder).
MODULE_HEADER_VERSION = 5.6.3

# WARNING: change `mkspecs/qconfig.pri` file's `QT_VERSION` instead of
# the `MODULE_VERSION` directly; unless testing/debugging temporarily.
load(qt_config)
MODULE_VERSION = $$QT_VERSION

# Ensures to log `build_pass` as well (if watch mode).
QMAKE_WATCH = *
#QMAKE_CXXFLAGS += /showIncludes
